version: '3.7'

services:
  postgres:
    image: postgres:13.2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
    ports:
      - 6432:5432
