# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test with Maven
        run: mvn clean package --file pom.xml

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/max-shop:latest


  deploy:

    runs-on: ubuntu-18.04

    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: 139.162.174.107
          username: github_client
          password: github_client
          script: |
            sudo docker-compose down -v
            sudo docker rmi $(docker images '${{ secrets.DOCKERHUB_USERNAME }}/max-shop' -a -q)
            sodo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/max-shop:latest
            sudo docker-compose up --build -d








